### ISSUE TITLE
Handling cases where there were zero residues remaining post bfactor filtering

### ISSUE THREAD

**Issue by Rohit-Satyam** [Elcock-Lab/AlphaFold2-Signal#1]
Hi @Elcock-Lab 

Thanks for such a wonderful paper and novel insights based on AF structures. I have a few queries about the code:

**Query1:** In the paper you said
>To prevent the counting of trivial contacts where the signal connects with the subsequent sequence, we exclude contacts involving a predefined number of residues immediately adjacent to the predicted cleavage site... Based on the data shown in these two figures, for all subsequent calculations, we chose to exclude atomic contacts involving one residue immediately before and one residue immediately after the cleavage site, and we used a distance cutoff of 4 Å to determine atomic contacts. 

That would mean that given an input length of signal peptide as "25" and considering that the predicted cleavage site is at the 26th residue, your code should take 1:24 residues as signal Peptide, and from the 28th residue onwards the rest of the protein. But I didn't see this behavior. I rather saw that contacts are computed for `1-25` residues. Is the code updated? Or maybe is misinterpreted `immediately adjacent to the predicted cleavage site` and what you meant here was `immediately next to the cleavage site` in which case the code is alright.

**Query2:** When using pLDDT score cutoff, there might be a scenario where out of 25 residues of the signal peptide, no residue meets the `90.0` bfactor threshold, in which case the no. of contacts with rest of the protein body will remain zero. I wrote a custom R function that mimics your fortran code and also provides some additional information. I observed `Q9TY95` in your benchmarking dataset. This protein has [signal peptide](https://www.uniprot.org/uniprotkb/Q9TY95/entry#ptm_processing) from 1-22. However, these starting residues have very-low plDDT score. In such case, there will be no residue left to calculate contacts and zero contacts here would not be here because signal peptide is pointing outwards. Did you filter out such proteins from benchmarking data?

```
cat signal_contacts.txt 
pdbname AF-Q9TY95-F1-model_v4.pdb      #res_sig:     22 #res_tot:    997 #res_sig_acc:     22 #res_rem_acc:    975 #res-res-conts:      0 #atm-atm-conts:      0
```

```
analyze_alphafold("AF-Q9TY95-F1-model_v4.pdb", 4.0, 22, 90.0, 1)
``` 

| Name                      | length_signalpeptide | length_protein | postbfacFiltered_signalP_res | medianSignalP_bfac | clevagesite_bfac | postbfacFiltered_rest_res | medianRest_bfac | res_res_conts | atm_atm_conts |
| ------------------------- | -------------------- | -------------- | ---------------------------- | ------------------ | ---------------- | ------------------------- | --------------- | ------------- | ------------- |
| AF-Q9TY95-F1-model_v4.pdb | 22                   | 997            | 0                            | 81.65              | 35.36            | 308                       | 81.65           | 0             | 0             |

As can be seen no. of resdues post bfac filtering `postbfacFiltered_signalP_res` are zero.

**Comment by Rohit-Satyam** [comment]
@Elcock-Lab any input would be appreciated.

**Comment by Elcock-Lab** [comment]
Rohit - so sorry to be so slow on this - I'll reach out to Venkat and we'll get back to you when we have some answers - again, sorry for not getting back to you quicker - best - Adrian

**Comment by Elcock-Lab** [comment]
Rohit - again, please accept my apologies for taking so long to get back to you - Venkat and I have both been very busy with other commitments, and I wanted to re-read the paper before responding - so here are our answers to your questions:

(1) For the example case of a signal that is 25 residues long, the cleavage site will be *between* residues 25 and 26. Since we skip one residue either side of the cleavage site, our approach then would be to only look for atomic contacts involving residues 1-24 and residues 27-onwards (not residues 28-onwards). I checked the code and it works correctly: the first do-loop is "do i1=1,nsignal-nskip", which equates to "do i1=1,25-1" ; the second do-loop is "do j1=nsignal+nskip+1,ires", which equates to "do j1=25+1+1,ires"...

(2) You are totally correct that the Q9TY95 has no atomic contacts between the signal and the rest of the protein that satisfy the PLDDT threshold. We did not exclude such cases from our analysis: instead, if this was a predictive scenario, we would interpret the absence of high-confidence atomic contacts between the signal and the rest of the protein as indicating that this is likely to be a correctly predicted signal.

I hope this helps - please let me know if I can be of any further help - I should be quicker to respond next time - best - Adrian
